name: Sync GitHub Teams & Users to Port.io
description: "Sync GitHub teams and their members to Port.io for better identity mapping."

inputs:
  token:
    description: "A GitHub Personal Access Token (PAT) with 'read:org' scope"
    required: true
  org:
    description: "GitHub organization to retrieve team and user data from"
    required: true
  port_client_id:
    description: "Client ID for Port.io API authentication"
    required: true
  port_client_secret:
    description: "Client Secret for Port.io API authentication"
    required: true

runs:
  using: "node20"
  main: "dist/index.js"

branding:
  icon: "users"
  color: "blue"